DROP TABLE IF EXISTS notes;

CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	uname TEXT NOT NULL,
	password TEXT NOT NULL,
	name TEXT NOT NULL
);

CREATE TABLE notes(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    note TEXT NOT NULL,
	ownerid INTEGER NOT NULL,
	sharedSet INTEGER NOT NULL
);
